"""add status to ImageData model

Revision ID: 9eb7208ca7a4
Revises: bf536fadf8bf
Create Date: 2023-04-24 12:42:58.753486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb7208ca7a4'
down_revision = 'bf536fadf8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('APPROVED', 'DECLINED', 'PENDING', name='imagedatastatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
